# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Richard Patching
tagline: Personal website and blog
description: The personal website and blog by Richard Patching.
email: richard@justaddpixels.com
description: > # this means to ignore newlines until "baseurl:"
  a blog by Richard Patching.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://richardpatching.com" # the base hostname & protocol for your site
twitter_username: patching_irl
github_username:  patchfx
disqus_shortname: richard-patching

twitter:
  username: patching_irl
  card: summary

social:
  name: Richard Patching
  links:
    - https://twitter.com/patching_irl
    - https://github.com/patchfx
    - https://instagram.com/richardpatching

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
markdown: kramdown
