# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Richard Patching
email: richard@justaddpixels.com
description: > # this means to ignore newlines until "baseurl:"
  a blog by Richard Patching.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://patchfx.github.com" # the base hostname & protocol for your site
twitter_username: disciplex
github_username:  patchfx
disqus_shortname: richard-patching

# Build settings
markdown: kramdown
